services:
  app:
    build:
      context: .
      args:
        user: ${APP_USER:-laravel}
        uid: ${APP_UID:-1000}
    image: task-management-app
    container_name: task-management-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
    env_file:
      - .env

  mysql:
    image: mysql:8.2
    container_name: task-management-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: task-management-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - laravel
    env_file:
      - .env
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    container_name: task-management-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel
    env_file:
      - .env

volumes:
  mysql_data:
  redis_data:

networks:
  laravel:
    driver: bridge
